name: MyRPG

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: make
